from typing import Protocol, Iterable, Optional
from src.models.course_model import Course

class ICourseRepository(Protocol):
    def list(self) -> Iterable[Course]: ...
    def get(self, course_id: int) -> Optional[Course]: ...
    def create(self, course: Course) -> Course: ...
    def update(self, course_id: int, **data) -> Course: ...
    def delete(self, course_id: int) -> None: ...
