from typing import Protocol, Iterable, Optional
from src.models.todo_model import Todo

class ITodoRepository(Protocol):
    def list(self) -> Iterable[Todo]: ...
    def get(self, todo_id: int) -> Optional[Todo]: ...
    def create(self, todo: Todo) -> Todo: ...
    def update(self, todo_id: int, **data) -> Todo: ...
    def delete(self, todo_id: int) -> None: ...
